server:
  port: 8088
# DataSourceProperties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml